name: jet_cli
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.14.2 <3.0.0'

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies:
  args: ^2.3.0
  jinja: ^0.4.0-dev.12
  recase: ^4.0.0
  universal_io: ^2.0.4
